-- ============================================================================
-- Scheduled reminders — REFERENCE ONLY.
--
-- The actual scheduling is done by the migration-provided RPC
-- public.setup_reminder_crons(p_cron_secret, p_functions_base)
-- (see supabase/migrations/20260831020000_cron_setup_fn.sql), called once
-- per environment with the service-role key:
--
--   curl -X POST "https://<ref>.supabase.co/rest/v1/rpc/setup_reminder_crons" \
--     -H "apikey: <service_role_key>" -H "Authorization: Bearer <service_role_key>" \
--     -H "Content-Type: application/json" \
--     -d '{"p_cron_secret":"<CRON_SECRET>","p_functions_base":"https://<ref>.supabase.co/functions/v1"}'
--
-- The secret must match the CRON_SECRET function secret on that project.
-- Applied to PROD (mikxrneopcwuldmykswq) on 2026-08-31. Dev is deliberately
-- left unscheduled so real devices/inboxes never get duplicate reminders.
--
-- Verify (service role): select public.list_reminder_crons();
--
-- Schedules (UTC; Brisbane = UTC+10):
--   daily-reminders-morning  30 21 * * *  -> 7:30am Brisbane
--   daily-reminders-evening  30 7 * * *   -> 5:30pm Brisbane (streak guard)
--   weekly-parent-summary    0 8 * * 0    -> 6pm Sunday Brisbane
--
-- To change a schedule: edit the function in a new migration and re-run the
-- RPC, or cron.unschedule('<jobname>') + cron.schedule(...) in the SQL editor.
-- ============================================================================
