/**
 * AI Module Generator - Content Generation
 * =========================================
 * 
 * This file contains:
 * - Configuration constants
 * - TypeScript type definitions
 * - Utility functions
 * - Claude API integration
 * - Page structure generator
 *
 * Content generation lives in generators-content.ts.
 * The HTML rendering is in a separate file: renderers.ts
 * NOTE: This module is stored under supabase/functions/_shared for edge bundling.
 */


// ====================
// CONFIGURATION
// ====================

const corsHeaders: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Max-Age": "86400",
  "Content-Type": "application/json",
};

// Claude configuration
const CLAUDE_MODEL = "claude-sonnet-4-20250514";
const CLAUDE_TEMPERATURE = 0.7;

// Token budgets
const TOKENS_METADATA = 1500;
const TOKENS_LESSON_BATCH = 6000;
const TOKENS_ACTIVITY = 2000;

// Timing
const JOB_TIMEOUT_MS = 8 * 60 * 1000;
const CACHE_TTL_MS = 5 * 60 * 1000;

// Page count range
const MIN_PAGES = 18;
const MAX_PAGES = 24;

// ====================
// TYPES
// ====================

type PageType = 
  | "cover"
  | "welcome"
  | "chapter-divider"
  | "lesson"
  | "interactive-lesson"
  | "checklist"
  | "reflection"
  | "quiz"
  | "drawing"
  | "breathing"
  | "scenario"
  | "feeling-thermometer"
  | "body-map"
  | "feeling-selector"
  | "calm-den-builder"
  | "action-plan"
  | "warning-signs"
  | "matching-activity"
  | "fill-in-story"
  | "coping-cards"
  | "gratitude-jar"
  | "sorting-activity"
  | "thought-bubbles"
  | "emoji-check-in"
  | "word-scramble"
  | "agree-disagree"
  | "comic-strip"
  | "affirmation-builder"
  | "weather-controller"
  | "power-up-collector"
  | "emotion-maze"
  | "strength-shield"
  | "feeling-volcano"
  | "spin-the-wheel"
  | "sticker-collector"
  | "mindful-adventure"
  | "emotion-detective"
  | "balloon-pop"
  | "treasure-hunt"
  | "monster-tamer"
  | "garden-grower"
  | "superhero-creator"
  | "feelings-orchestra"
  | "calm-aquarium"
  | "rocket-launcher"
  | "magic-potion"
  | "feelings-bingo"
  | "summary"
  | "completion"
  | "admin-verification";

interface PageTemplate {
  type: PageType;
  starReward: boolean;
}

/**
 * Self-verification report generated by AI audit pass
 * Admin-only page shown at the end of the module
 */
interface VerificationReport {
  theoriesUsed: Array<{
    theoryName: string;
    whereOperationalised: string;
  }>;
  ageRangeTheoriesApplied: string;
  subSkillAlignment: string;
  superSkillAlignment: string;
  brainTownAnalogyUsage: string;
  unselectedConceptsIntroduced: string[];
  toneComplianceNotes: string;
  claimTypes: string;
  australianEnglishCheck: string;
  overallAssessment: string;
  flaggedIssues: string[];
  autoRevisions: string[];
}

/**
 * Module summary for week-over-week continuity
 */
interface ModuleSummary {
  summary: string;
  keyConceptsCovered: string[];
  skillsIntroduced: string[];
  characterProgressionNotes: string;
}

interface ModuleMetadata {
  title: string;
  subtitle: string;
  shortDescription: string;
  description: string;
  series: string;
  targetAge: string;
  theme: string;
  characterName: string;
  characterEmoji: string;
  characterType?: string;
}

/**
 * Age range data from the database
 * Simplified: Only display_name, language_guidelines, and developmental_stage are sent to AI
 */
interface AgeRangeData {
  id: string;
  age_range: string;
  display_name: string;
  language_guidelines: string;
  developmental_stage: string;
  cognitive_abilities: string;
  emotional_capacity: string;
  attention_span: string | null;
  vocabulary_level: string;
  sentence_complexity: string;
  abstract_thinking: string;
  neurodivergent_adaptations: string | null;
  trauma_sensitive_notes: string | null;
  ageRange?: string;
  ageMin?: number;
  ageMax?: number;
  displayName?: string;
  languageGuidelines?: string;
  developmentalStage?: string;
  cognitiveAbilities?: string;
  emotionalCapacity?: string;
  attentionSpan?: string | null;
  vocabularyLevel?: string;
  sentenceComplexity?: string;
  abstractThinking?: string;
  neurodivergentAdaptations?: string | null;
  traumaSensitiveNotes?: string | null;
}

/**
 * Core theory data from the database
 * Simplified: Only description and primary_researchers (key theorists) are sent to AI
 */
interface CoreTheoryData {
  id: string;
  theory_name: string;
  description: string;
  primary_researchers: string | null;
}

// Series data from the database
interface SeriesInfo {
  label: string;
  character_type: string;
  emoji: string;
  character_image_url?: string | null;
}

interface LessonContent {
  heading: string;
  paragraphs: string[];
  calloutTitle?: string;
  calloutText?: string;
  tipText?: string;
  danielInteraction?: string; // NEW: Specific Daniel dialogue or interaction note
}

interface ChapterDivider {
  chapterNumber: number;
  chapterTitle: string;
  chapterSubtitle: string;
}

interface ChecklistContent {
  heading: string;
  instructions: string;
  items: string[];
}

interface ReflectionContent {
  heading: string;
  prompt: string;
  placeholder: string;
}

interface QuizContent {
  heading: string;
  question: string;
  answers: Array<{
    text: string;
    isCorrect: boolean;
    feedback: string;
  }>;
}

interface DrawingContent {
  heading: string;
  instructions: string;
  promptQuestion: string;
}

interface BreathingContent {
  heading: string;
  instructions: string;
  inhaleText: string;
  holdText: string;
  exhaleText: string;
}

interface ScenarioContent {
  heading: string;
  scenario: string;
  question: string;
  options: Array<{
    text: string;
    feedback: string;
    isGood: boolean;
  }>;
}

interface SummaryContent {
  heading: string;
  takeaways: string[];
  encouragement: string;
}

interface CompletionContent {
  heading: string;
  celebrationText: string;
  nextStepsText: string;
}

/**
 * Grown-up note content for parent/caregiver guidance
 * Appears as a collapsible accordion on select pages
 */
interface GrownUpNote {
  evidenceBase: string;      // e.g., "Growth Mindset (Dweck)", "CBT Self-Talk"
  briefExplanation: string;  // 1-2 sentences explaining the concept
  parentPrompts: string[];   // 2-3 conversation starters for parents
}

/**
 * Maps page types to their evidence bases for grown-up notes
 */
const PAGE_TYPE_EVIDENCE_MAP: Record<string, { evidenceBase: string; conceptArea: string }> = {
  "lesson": { evidenceBase: "Social-Emotional Learning", conceptArea: "foundational concepts" },
  "interactive-lesson": { evidenceBase: "Active Learning Theory", conceptArea: "engagement and retention" },
  "breathing": { evidenceBase: "Mindfulness & Relaxation Response", conceptArea: "self-regulation" },
  "feeling-thermometer": { evidenceBase: "Emotional Literacy", conceptArea: "emotional awareness" },
  "body-map": { evidenceBase: "Somatic Awareness / Interoception", conceptArea: "body-emotion connection" },
  "scenario": { evidenceBase: "Social Problem-Solving", conceptArea: "perspective-taking" },
  "thought-bubbles": { evidenceBase: "Cognitive Behavioural Therapy (CBT)", conceptArea: "thought reframing" },
  "affirmation-builder": { evidenceBase: "Positive Psychology / Self-Compassion", conceptArea: "positive self-talk" },
  "calm-den-builder": { evidenceBase: "Safe Space / Regulation Zones", conceptArea: "self-soothing strategies" },
  "action-plan": { evidenceBase: "Goal-Setting Theory", conceptArea: "planning and agency" },
  "warning-signs": { evidenceBase: "Early Intervention / Self-Monitoring", conceptArea: "recognising triggers" },
  "emotion-maze": { evidenceBase: "Decision-Making & Impulse Control", conceptArea: "emotional regulation pathways" },
  "weather-controller": { evidenceBase: "Emotional Regulation / Zones of Regulation", conceptArea: "managing emotional intensity" },
  "coping-cards": { evidenceBase: "Coping Skills Toolkit", conceptArea: "building a personal toolkit" },
  "gratitude-jar": { evidenceBase: "Positive Psychology / Gratitude Practice", conceptArea: "wellbeing and positivity" },
  "reflection": { evidenceBase: "Metacognition / Reflective Practice", conceptArea: "self-awareness" },
  "monster-tamer": { evidenceBase: "Externalisation (Narrative Therapy)", conceptArea: "separating self from feelings" },
  "superhero-creator": { evidenceBase: "Strength-Based Approaches", conceptArea: "identifying personal strengths" },
  "strength-shield": { evidenceBase: "Resilience & Protective Factors", conceptArea: "building resilience" },
};

interface FeelingThermometerContent {
  heading: string;
  instructions: string;
  lowLabel: string;
  highLabel: string;
  followUpQuestion: string;
}

interface BodyMapContent {
  heading: string;
  instructions: string;
  bodyParts: Array<{
    name: string;
    emoji: string;
    description: string;
  }>;
}

interface FeelingSelectorContent {
  heading: string;
  instructions: string;
  feelings: Array<{
    name: string;
    emoji: string;
    color: string;
  }>;
  followUpQuestion: string;
}

interface CalmDenBuilderContent {
  heading: string;
  storyText: string;
  instructions: string;
  items: Array<{
    id: string;
    name: string;
    emoji: string;
  }>;
  locationQuestion: string;
}

interface ActionPlanContent {
  heading: string;
  instructions: string;
  steps: Array<{
    stepNumber: number;
    title: string;
    prompt: string;
    placeholder: string;
  }>;
}

interface WarningSingsContent {
  heading: string;
  instructions: string;
  categories: Array<{
    category: string;
    emoji: string;
    examples: string[];
  }>;
}

interface MatchingActivityContent {
  heading: string;
  instructions: string;
  pairs: Array<{
    situation: string;
    feeling: string;
    emoji: string;
  }>;
}

// NEW: Interactive lesson with embedded mini-activities
interface InteractiveLessonContent {
  heading: string;
  introText: string;
  interactionType: "poll" | "circle-one" | "fill-blank" | "rate-scale" | "true-false";
  interactionPrompt: string;
  interactionOptions?: string[];
  correctAnswerIndex?: number; // For poll/circle-one questions with a correct answer
  followUpText: string;
  mascotComment: string;
  danielInteraction?: string; // NEW: Specific Daniel dialogue or interaction note
}

interface FillInStoryContent {
  heading: string;
  instructions: string;
  storyTemplate: string;
  blanks: Array<{
    id: string;
    hint: string;
    category: string;
  }>;
  reflection: string;
}

interface CopingCardsContent {
  heading: string;
  instructions: string;
  categories: Array<{
    name: string;
    emoji: string;
    color: string;
    strategies: string[];
  }>;
  personalCardPrompt: string;
}

interface GratitudeJarContent {
  heading: string;
  introText: string;
  promptCategories: Array<{
    category: string;
    emoji: string;
    prompt: string;
  }>;
  encouragement: string;
}

interface SortingActivityContent {
  heading: string;
  instructions: string;
  categories: Array<{
    name: string;
    emoji: string;
    color: string;
  }>;
  items: Array<{
    text: string;
    correctCategory: string;
    explanation: string;
  }>;
}

interface ThoughtBubblesContent {
  heading: string;
  scenario: string;
  characterEmoji: string;
  unhelpfulThought: string;
  helpfulPrompt: string;
  exampleHelpful: string;
  reflection: string;
}

interface EmojiCheckInContent {
  heading: string;
  instructions: string;
  timePoints: Array<{
    label: string;
    emoji: string;
  }>;
  moodOptions: Array<{
    emoji: string;
    label: string;
    color: string;
  }>;
  patternQuestion: string;
}

interface WordScrambleContent {
  heading: string;
  instructions: string;
  words: Array<{
    scrambled: string;
    answer: string;
    hint: string;
    emoji: string;
  }>;
  completionMessage: string;
}

interface AgreeDisagreeContent {
  heading: string;
  instructions: string;
  statements: Array<{
    statement: string;
    insight: string;
  }>;
  reflection: string;
}

interface ComicStripContent {
  heading: string;
  scenario: string;
  panels: Array<{
    panelNumber: number;
    prompt: string;
    placeholder: string;
  }>;
  sharePrompt: string;
}

interface AffirmationBuilderContent {
  heading: string;
  instructions: string;
  starters: string[];
  middles: string[];
  endings: string[];
  decorationEmojis: string[];
  savePrompt: string;
}

// ====================
// v5 NEW CHALLENGE INTERFACES
// ====================

interface WeatherControllerContent {
  heading: string;
  instructions: string;
  weatherType: "storm" | "rain" | "fog" | "heat";
  calmingActions: Array<{
    id: string;
    label: string;
    emoji: string;
    points: number;
    feedbackText: string;
  }>;
  winText: string;
  encouragement: string;
}

interface PowerUpCollectorContent {
  heading: string;
  instructions: string;
  powerUps: Array<{
    id: string;
    name: string;
    emoji: string;
    description: string;
    isPositive: boolean;
  }>;
  targetCount: number;
  winText: string;
  tipText: string;
}

interface EmotionMazeContent {
  heading: string;
  instructions: string;
  startEmotion: { name: string; emoji: string };
  goalEmotion: { name: string; emoji: string };
  pathChoices: Array<{
    step: number;
    situation: string;
    options: Array<{
      text: string;
      emoji: string;
      isCorrect: boolean;
      feedback: string;
    }>;
  }>;
  completionMessage: string;
}

interface StrengthShieldContent {
  heading: string;
  instructions: string;
  shieldSections: Array<{
    id: string;
    title: string;
    emoji: string;
    prompt: string;
    placeholder: string;
  }>;
  decorations: string[];
  completionMessage: string;
}

interface FeelingVolcanoContent {
  heading: string;
  instructions: string;
  triggerScenario: string;
  coolingActions: Array<{
    id: string;
    action: string;
    emoji: string;
    coolingPower: number;
  }>;
  levels: Array<{
    level: number;
    emoji: string;
    label: string;
    color: string;
  }>;
  safeMessage: string;
}

// v6 NEW FUN INTERACTIVE LESSON TYPES
interface SpinTheWheelContent {
  heading: string;
  instructions: string;
  wheelQuestion: string;
  segments: Array<{
    id: string;
    label: string;
    emoji: string;
    color: string;
    response: string;
  }>;
  celebrationMessage: string;
}

interface StickerCollectorContent {
  heading: string;
  storyText: string;
  instructions: string;
  challenges: Array<{
    id: string;
    emoji: string;
    title: string;
    description: string;
  }>;
  totalStickers: number;
  completionMessage: string;
}

interface MindfulAdventureContent {
  heading: string;
  introText: string;
  scenes: Array<{
    id: string;
    sceneName: string;
    emoji: string;
    description: string;
    mindfulPrompt: string;
    placeholder: string;
  }>;
  closingMessage: string;
}

interface EmotionDetectiveContent {
  heading: string;
  caseDescription: string;
  instructions: string;
  clues: Array<{
    id: string;
    clueEmoji: string;
    clueText: string;
  }>;
  emotionOptions: Array<{
    emotion: string;
    emoji: string;
    explanation: string;
    isCorrect: boolean;
  }>;
  revelationMessage: string;
}

// ====================
// v7 NEW HIGHLY INTERACTIVE GAME INTERFACES
// ====================

interface BalloonPopContent {
  heading: string;
  instructions: string;
  scenario: string;
  balloons: Array<{
    id: string;
    worryText: string;
    emoji: string;
    color: string;
    popResponse: string;
  }>;
  calmingTools: Array<{
    id: string;
    tool: string;
    emoji: string;
    power: number;
  }>;
  victoryMessage: string;
}

interface TreasureHuntContent {
  heading: string;
  storyIntro: string;
  instructions: string;
  locations: Array<{
    id: string;
    name: string;
    emoji: string;
    description: string;
    treasure: {
      name: string;
      emoji: string;
      lesson: string;
    };
    question: string;
    placeholder: string;
  }>;
  mapEmoji: string;
  completionMessage: string;
}

interface MonsterTamerContent {
  heading: string;
  instructions: string;
  monster: {
    name: string;
    emotion: string;
    emoji: string;
    startingSize: number;
    description: string;
  };
  tamingActions: Array<{
    id: string;
    action: string;
    emoji: string;
    shrinkPower: number;
    message: string;
  }>;
  stages: Array<{
    level: number;
    emoji: string;
    description: string;
  }>;
  friendMessage: string;
}

interface GardenGrowerContent {
  heading: string;
  instructions: string;
  gardenStory: string;
  plants: Array<{
    id: string;
    name: string;
    emoji: string;
    feeling: string;
    growthStages: string[];
    nurturingAction: string;
  }>;
  wateringCan: {
    emoji: string;
    actions: string[];
  };
  harvestMessage: string;
}

interface SuperheroCreatorContent {
  heading: string;
  instructions: string;
  storyIntro: string;
  heroElements: {
    powers: Array<{
      id: string;
      name: string;
      emoji: string;
      description: string;
    }>;
    costumes: Array<{
      id: string;
      name: string;
      emoji: string;
      color: string;
    }>;
    sidekicks: Array<{
      id: string;
      name: string;
      emoji: string;
      ability: string;
    }>;
  };
  missionPrompt: string;
  heroNamePrompt: string;
  completionMessage: string;
}

interface FeelingsOrchestraContent {
  heading: string;
  instructions: string;
  orchestraStory: string;
  instruments: Array<{
    id: string;
    name: string;
    emoji: string;
    feeling: string;
    sound: string;
    color: string;
  }>;
  compositionPrompt: string;
  performanceMessage: string;
}

interface CalmAquariumContent {
  heading: string;
  instructions: string;
  aquariumStory: string;
  creatures: Array<{
    id: string;
    name: string;
    emoji: string;
    calmingTrait: string;
    movement: string;
  }>;
  decorations: Array<{
    id: string;
    name: string;
    emoji: string;
    calmingEffect: string;
  }>;
  breathingBubbles: {
    inhaleTime: number;
    exhaleTime: number;
    message: string;
  };
  peaceMessage: string;
}

interface RocketLauncherContent {
  heading: string;
  instructions: string;
  missionBriefing: string;
  planets: Array<{
    id: string;
    name: string;
    emoji: string;
    feeling: string;
    color: string;
    activity: string;
    reward: string;
  }>;
  fuelActions: Array<{
    id: string;
    action: string;
    emoji: string;
    fuelAmount: number;
  }>;
  launchSequence: string[];
  returnMessage: string;
}

interface MagicPotionContent {
  heading: string;
  instructions: string;
  cauldronStory: string;
  ingredients: Array<{
    id: string;
    name: string;
    emoji: string;
    feeling: string;
    sparkle: string;
    description: string;
  }>;
  recipes: Array<{
    potionName: string;
    emoji: string;
    requiredIngredients: string[];
    effect: string;
    color: string;
  }>;
  brewingSteps: string[];
  magicMessage: string;
}

interface FeelingsBingoContent {
  heading: string;
  instructions: string;
  bingoStory: string;
  squares: Array<{
    id: string;
    emoji: string;
    feeling: string;
    challenge: string;
  }>;
  freeSpace: {
    emoji: string;
    message: string;
  };
  bingoPatterns: string[];
  winMessage: string;
}

interface GeneratedContent {
  metadata: ModuleMetadata;
  welcome: { heading: string; paragraphs: string[] };
  chapters: ChapterDivider[];
  lessons: LessonContent[];
  interactiveLessons: InteractiveLessonContent[];
  checklists: ChecklistContent[];
  reflections: ReflectionContent[];
  quizzes: QuizContent[];
  drawings: DrawingContent[];
  breathing: BreathingContent;
  scenarios: ScenarioContent[];
  feelingThermometers: FeelingThermometerContent[];
  bodyMaps: BodyMapContent[];
  feelingSelectors: FeelingSelectorContent[];
  calmDenBuilders: CalmDenBuilderContent[];
  actionPlans: ActionPlanContent[];
  warningSigns: WarningSingsContent[];
  matchingActivities: MatchingActivityContent[];
  // NEW
  fillInStories: FillInStoryContent[];
  copingCards: CopingCardsContent[];
  gratitudeJars: GratitudeJarContent[];
  sortingActivities: SortingActivityContent[];
  thoughtBubbles: ThoughtBubblesContent[];
  emojiCheckIns: EmojiCheckInContent[];
  wordScrambles: WordScrambleContent[];
  agreeDisagrees: AgreeDisagreeContent[];
  comicStrips: ComicStripContent[];
  affirmationBuilders: AffirmationBuilderContent[];
  // v5 NEW CHALLENGE TYPES
  weatherControllers: WeatherControllerContent[];
  powerUpCollectors: PowerUpCollectorContent[];
  emotionMazes: EmotionMazeContent[];
  strengthShields: StrengthShieldContent[];
  feelingVolcanoes: FeelingVolcanoContent[];
  // v6 NEW FUN INTERACTIVE LESSONS
  spinTheWheels: SpinTheWheelContent[];
  stickerCollectors: StickerCollectorContent[];
  mindfulAdventures: MindfulAdventureContent[];
  emotionDetectives: EmotionDetectiveContent[];
  balloonPops: BalloonPopContent[];
  treasureHunts: TreasureHuntContent[];
  monsterTamers: MonsterTamerContent[];
  gardenGrowers: GardenGrowerContent[];
  superheroCreators: SuperheroCreatorContent[];
  feelingsOrchestras: FeelingsOrchestraContent[];
  calmAquariums: CalmAquariumContent[];
  rocketLaunchers: RocketLauncherContent[];
  magicPotions: MagicPotionContent[];
  feelingsBingos: FeelingsBingoContent[];
  summary: SummaryContent;
  completion: CompletionContent;
  verificationReport?: VerificationReport;
  moduleSummary?: ModuleSummary;
  grownUpNotes?: Record<number, GrownUpNote>; // Object mapping page index to GrownUpNote
}

// Cache
let cachedSettings: { claude_api_key: string; fetchedAt: number } | null = null;

// ====================
// UTILITIES
// ====================

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: corsHeaders });
}

function escapeHtml(s: string): string {
  return (s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// For use inside template literals that will be rendered at runtime
function escapeForTemplate(s: string): string {
  return escapeHtml(s)
    .replace(/\\/g, "\\\\")  // Escape backslashes first
    .replace(/`/g, "\\`")    // Escape backticks
    .replace(/\$/g, "\\$")   // Escape dollar signs to prevent ${} interpretation
    .replace(/'/g, "\\'");   // Escape single quotes for onclick handlers
}

// For use in onclick handlers where single quotes wrap the string
function escapeForOnclick(s: string): string {
  return (s ?? "")
    .replace(/\\/g, "\\\\")  // Escape backslashes first
    .replace(/'/g, "\\'")    // Escape single quotes
    .replace(/"/g, "&quot;") // Escape double quotes for HTML attribute
    .replace(/</g, "&lt;")   // Escape < for HTML safety
    .replace(/>/g, "&gt;");  // Escape > for HTML safety
}

function cleanJsonResponse(text: string): string {
  let t = (text ?? "").trim();
  t = t.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");
  t = t.replace(/[""]/g, '"').replace(/['']/g, "'");
  const first = t.indexOf("{");
  const last = t.lastIndexOf("}");
  if (first >= 0 && last > first) {
    t = t.slice(first, last + 1);
  }
  t = t.replace(/,\s*([}\]])/g, "$1");
  return t.trim();
}

function safeJsonParse<T>(raw: string): T | null {
  try {
    return JSON.parse(cleanJsonResponse(raw)) as T;
  } catch {
    return null;
  }
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getAgeRangeKey(ageRange: string, ageData?: AgeRangeData): string {
  // Use age_range from database if available
  if (ageData?.age_range) {
    return ageData.age_range;
  }

  // Fall back to parsing the provided ageRange string
  const normalized = (ageRange || "").replace(/[–—]/g, "-").trim();
  const match = normalized.match(/(\d{1,2})\s*-\s*(\d{1,2})/);
  if (match) {
    return `${match[1]}-${match[2]}`;
  }

  return normalized;
}

function buildAgeRangeStyleGuide(ageRange: string, ageData?: AgeRangeData): string {
  const normalized = getAgeRangeKey(ageRange, ageData);
  switch (normalized) {
    case "6-8":
      return `
EARLY CHILDHOOD (6-8) — Concrete Learners
- Very short text blocks (1-2 short sentences per paragraph) with frequent line breaks.
- Keep most teaching chunks under ~40-70 words before shifting to an activity.
- Use simple, concrete words; avoid abstract terms unless explained with an immediate example.
- Use playful, reassuring tone with lots of encouragement.
- Activities should be highly guided with clear, single-step instructions.
- Prefer visuals, emojis, and imaginative play; minimal reading required.
- Limit concepts to "here and now" experiences (feelings, body cues, simple choices).
`.trim();
    case "9-11":
      return `
LATE CHILDHOOD (9-11) — Bridge Thinkers
- Keep text concise: usually 1-3 short sentences per paragraph.
- Keep most teaching blocks to ~70-120 words before moving to an activity.
- Introduce new vocabulary with quick definitions or examples.
- Balance playful tone with growing independence and responsibility.
- Activities can be 2-3 steps with light reflection.
- Encourage perspective-taking and cause-and-effect reasoning.
- Use relatable school/friend scenarios and simple problem-solving.
`.trim();
    case "12-14":
      return `
EARLY ADOLESCENCE (12-14) — Transition Thinkers
- Medium text blocks (2-4 sentences) with clear structure and spacing.
- Keep teaching sections focused (~90-160 words), then move to choice-based interaction.
- Use more sophisticated vocabulary, but define less-familiar terms naturally in context.
- Respect autonomy; avoid babyish phrasing.
- Activities can be multi-step with choice and self-directed reflection.
- Introduce abstract ideas (values, identity, beliefs) with concrete examples.
- Use peer/social dynamics and "real-life" challenges.
`.trim();
    case "15-18":
      return `
MID-LATE ADOLESCENCE (15-18) — Abstract Integrators
- Structured text blocks (3-5 sentences) with strong purpose and minimal repetition.
- Keep explanatory passages concise (~120-220 words) before prompting analysis or action.
- Use mature, nuanced language; avoid oversimplification.
- Encourage metacognition, goal-setting, and personal agency.
- Activities can be multi-part with deeper reflection and planning.
- Emphasize abstract reasoning, systems thinking, and long-term consequences.
- Use authentic, teen-relevant contexts (relationships, stress, future planning).
`.trim();
    default:
      return `
AGE-SPECIFIC DIFFERENTIATION
- Match text length, vocabulary, and activity complexity to the stated age range.
- Ensure a clearly distinct tone and depth between age groups.
`.trim();
  }
}

/**
 * Returns age-specific formatting instructions for content generators.
 * These provide concrete, measurable requirements that differ by age group.
 */
function getAgeSpecificFormatting(ageRange: string, ageData?: AgeRangeData): {
  paragraphLength: string;
  sentenceCount: string;
  vocabularyLevel: string;
  toneDescription: string;
  instructionStyle: string;
  contentComplexity: string;
  welcomeParagraphs: string;
  lessonParagraphs: string;
  itemCount: string;
} {
  const normalized = getAgeRangeKey(ageRange, ageData);
  
  switch (normalized) {
    case "6-8":
      return {
        paragraphLength: "1-2 short sentences maximum per paragraph",
        sentenceCount: "Keep most sentences around 6-10 words; avoid multi-clause structures",
        vocabularyLevel: "Use simple everyday words; explain any unfamiliar word immediately",
        toneDescription: "Super friendly, warm, and playful - like talking to a young friend",
        instructionStyle: "One simple step at a time, use 'Let's...' and 'Can you...'",
        contentComplexity: "Focus on feelings they can see/feel RIGHT NOW, use lots of emojis",
        welcomeParagraphs: "2 very short paragraphs (1-2 sentences each), big friendly energy",
        lessonParagraphs: "1-2 short paragraphs max, then activity prompts",
        itemCount: "3-4 items maximum, each very short"
      };
    case "9-11":
      return {
        paragraphLength: "1-3 sentences per paragraph, with frequent visual breaks",
        sentenceCount: "Aim for 8-14 words per sentence; avoid dense compound sentences",
        vocabularyLevel: "Plain school-age vocabulary; define any new term in-context immediately",
        toneDescription: "Friendly and encouraging, treats them as capable learners",
        instructionStyle: "Clear 2-3 step instructions, can include 'why' briefly",
        contentComplexity: "Cause-and-effect is appropriate, but keep explanations brief and concrete",
        welcomeParagraphs: "2 short paragraphs (1-2 sentences each)",
        lessonParagraphs: "1-2 short teaching paragraphs, then move quickly into interaction",
        itemCount: "4-5 items"
      };
    case "12-14":
      return {
        paragraphLength: "2-4 sentences per paragraph with clear section breaks",
        sentenceCount: "Average 10-18 words with occasional shorter emphasis sentences",
        vocabularyLevel: "Growing academic vocabulary; define technical/abstract terms in-line",
        toneDescription: "Supportive but not babyish, peer-like and respectful",
        instructionStyle: "Multi-step with some autonomy and choice",
        contentComplexity: "Can discuss abstract concepts with concrete examples, deeper reflection",
        welcomeParagraphs: "2 concise paragraphs (2-3 sentences each)",
        lessonParagraphs: "2 short teaching paragraphs then applied activity",
        itemCount: "5-6 items"
      };
    case "15-18":
      return {
        paragraphLength: "3-5 sentences per paragraph; avoid unnecessary length",
        sentenceCount: "Natural mature syntax with controlled length (roughly 12-22 words typical)",
        vocabularyLevel: "Mature vocabulary, nuanced language",
        toneDescription: "Respectful, empowering, treats them as near-adults",
        instructionStyle: "Self-directed with meaningful choices and deeper exploration",
        contentComplexity: "Abstract reasoning, metacognition, long-term planning",
        welcomeParagraphs: "2 focused paragraphs",
        lessonParagraphs: "2-3 purposeful paragraphs followed by reflective action",
        itemCount: "5-7 items with depth"
      };
    default:
      return {
        paragraphLength: "2-3 sentences per paragraph",
        sentenceCount: "Age-appropriate sentence length",
        vocabularyLevel: "Match vocabulary to stated age range",
        toneDescription: "Warm and encouraging",
        instructionStyle: "Clear and supportive",
        contentComplexity: "Appropriate for the age range",
        welcomeParagraphs: "2-3 paragraphs",
        lessonParagraphs: "2-3 paragraphs",
        itemCount: "4-5 items"
      };
  }
}

function getAgeDataText(
  ageData: AgeRangeData,
  snakeKey: keyof AgeRangeData,
  camelKey: keyof AgeRangeData
): string {
  const record = ageData as unknown as Record<string, unknown>;
  return String(record[snakeKey] ?? record[camelKey] ?? "");
}

function getAgeDataOptionalText(
  ageData: AgeRangeData,
  snakeKey: keyof AgeRangeData,
  camelKey: keyof AgeRangeData
): string | null {
  const record = ageData as unknown as Record<string, unknown>;
  const value = record[snakeKey] ?? record[camelKey];
  if (value == null) {
    return null;
  }
  return String(value);
}

/**
 * Builds an enhanced, psychology-informed content brief
 * NOW INCLUDES: secondary theories, diagnosis adaptations, NDIS, SEDI
 * CONTENT STYLE: Less text, less Daniel, more activities
 */
function buildEnhancedContentBrief(resolved: {
  title: string;
  ageRange: string;
  ageData: AgeRangeData;
  theoryData: CoreTheoryData;
  brainTownAnalogy: string;
  additionalContext: string;
  secondaryTheories?: string[];
  neuroscienceConcept?: string;
  diagnosisPathways?: string[];
  fasdStrategies?: string;
  ndisDomain?: string;
  dssSedi?: string;
  moduleObjective?: string;
  facilitatorTip?: string;
  reflectionPrompt?: string;
  rewardText?: string;
  previousModuleSummary?: string;
  weekNumber?: number;
  superSkillName?: string;
  superSkillDescription?: string;
  subSkillName?: string;
  subSkillDescription?: string;
}): string {
  const { 
    ageData, theoryData, brainTownAnalogy, additionalContext, title, ageRange,
    secondaryTheories, neuroscienceConcept, diagnosisPathways, fasdStrategies,
    ndisDomain, dssSedi, moduleObjective, facilitatorTip, reflectionPrompt, rewardText,
    previousModuleSummary, weekNumber, superSkillName, superSkillDescription,
    subSkillName, subSkillDescription
  } = resolved;
  
  const ageStyleGuide = buildAgeRangeStyleGuide(ageRange, ageData);
  const displayName = getAgeDataText(ageData, "display_name", "displayName");
  const languageGuidelines = getAgeDataText(ageData, "language_guidelines", "languageGuidelines");
  
  return `
=== MODULE BRIEF ===
Title: ${title}
Target Age: ${ageRange} (${displayName})
${superSkillName ? `Super Skill: ${superSkillName}${superSkillDescription ? ` — ${superSkillDescription}` : ''}` : ''}
${subSkillName ? `Sub-Skill: ${subSkillName}${subSkillDescription ? ` — ${subSkillDescription}` : ''}` : ''}
${moduleObjective ? `Objective: ${moduleObjective}` : ''}

CRITICAL — NON-NEGOTIABLE REQUIREMENTS:
- The module title MUST be exactly "${title}" — do NOT change, rephrase, or create a different title.
- The target age range MUST be exactly "${ageRange}" — do NOT change this.
- The primary theory MUST be "${theoryData.theory_name}" — all content must operationalise this theory.
- The Brain Town analogy MUST be woven throughout the content (see BRAIN TOWN ANALOGY section).
${superSkillName ? `- All content must align with the Super Skill: "${superSkillName}".` : ''}
${subSkillName ? `- All content must focus on building the Sub-Skill: "${subSkillName}".` : ''}

${additionalContext ? `=== HIGH-PRIORITY CREATOR INSTRUCTIONS (MUST FOLLOW) ===
${additionalContext}

NON-NEGOTIABLE:
- Treat every instruction above as a hard requirement.
- If these instructions conflict with generic style patterns, prioritize these instructions.
- Use the exact framing, metaphors, and wording requirements when specified.
` : ''}

=== CRITICAL CONTENT STYLE RULES ===
🚨 READ THESE FIRST - MOST IMPORTANT 🚨

1. SHORTER TEXT BLOCKS
   - Each paragraph: 2-4 sentences MAX
   - Each page should have small, scannable chunks
   - Break up long explanations into bite-sized pieces

2. LESS DANIEL DIALOGUE
   - Daniel appears OCCASIONALLY (2-3 times per module), not constantly
   - Most content is direct teaching, not Daniel talking
   - When Daniel does appear, keep it to 1-2 sentences
   - Example: ✅ "Daniel noticed his hands felt shaky." ❌ "Daniel said, 'Hey, I'm noticing my hands feel shaky, and I wonder what that means...'"

3. MORE ACTIVITIES, LESS READING
   - Prioritize interactive elements
   - Use visual cues, prompts, choices
   - Children should DO more than READ
   
4. CHUNK EVERYTHING
   - Use short paragraphs
   - Add visual breaks
   - One idea per section

=== PSYCHOLOGICAL FOUNDATION ===
PRIMARY THEORY: ${theoryData.theory_name}
${theoryData.description}

IMPORTANT: This theory MUST be the central framework for ALL content in this module.
Every lesson, activity, and interactive element should operationalise "${theoryData.theory_name}" in a child-friendly way.
${superSkillName ? `The Super Skill "${superSkillName}" provides the overarching skill domain.` : ''}
${subSkillName ? `The Sub-Skill "${subSkillName}"${subSkillDescription ? ` (${subSkillDescription})` : ''} is the specific focus area within that domain.` : ''}

${secondaryTheories && secondaryTheories.length > 0 ? `SUPPORTING THEORIES (secondary, supplement the primary): ${secondaryTheories.join(', ')}` : ''}

=== LANGUAGE GUIDELINES ===
${languageGuidelines}

${ageStyleGuide}

=== BRAIN TOWN ANALOGY (MUST BE USED THROUGHOUT) ===
${brainTownAnalogy}

CRITICAL: This Brain Town analogy MUST appear in the generated content:
- Introduce it early (welcome page or first lesson)
- Reference it in at least 2-3 lessons and activities throughout the module
- Use the analogy to explain the primary theory concepts in a child-friendly way
- Keep each Brain Town reference SHORT (2-3 sentences max) but make sure it appears

${neuroscienceConcept ? `=== NEUROSCIENCE TIE-IN ===
Include brief mention of: ${neuroscienceConcept}
Keep it simple - 1-2 sentences only.
` : ''}

${diagnosisPathways && diagnosisPathways.length > 0 ? `=== DIAGNOSIS ADAPTATIONS ===
Adapt for: ${diagnosisPathways.map(d => d.toUpperCase()).join(', ')}

${diagnosisPathways.includes('fasd') ? (fasdStrategies ? `FASD: ${fasdStrategies}` : 'FASD: Use concrete visuals, one-step instructions, memory scaffolds') : ''}
${diagnosisPathways.includes('adhd') ? 'ADHD: Minimal text, movement breaks, chunked info' : ''}
${diagnosisPathways.includes('asd') ? 'ASD: Literal language, explicit instructions, clear structure' : ''}
${diagnosisPathways.includes('pda') ? 'PDA: Offer choices, avoid directives, respect autonomy' : ''}
${diagnosisPathways.includes('trauma') ? 'Trauma: Safety first, no surprises, clear opt-outs' : ''}
` : ''}

${ndisDomain || dssSedi ? `=== OUTCOME FRAMEWORKS ===
${ndisDomain ? `NDIS Domain: ${ndisDomain}` : ''}
${dssSedi ? `DSS SEDI: ${dssSedi}` : ''}
` : ''}

${facilitatorTip ? `=== FACILITATOR GUIDANCE ===
${facilitatorTip}
` : ''}

=== GENERATION RULES ===
1. Keep ALL paragraphs SHORT (2-4 sentences MAX)
2. Use Daniel SPARINGLY - 2-3 brief appearances per module, but ALWAYS mention "Daniel" by name at least once
3. Focus on ACTIVITIES over explanations
4. Break content into SMALL chunks
5. More DOING, less READING
6. Apply "${theoryData.theory_name}" theory correctly — this is the PRIMARY framework for ALL content
7. Use the Brain Town analogy throughout (introduce early, reference in lessons and activities)
8. CHILD AS TOWN PLANNER: Frame the child as the "town planner" of their Brain Town at least once
9. THEORY CITATION: Mention the primary theory name AND include the researcher's surname in the content
10. LEARNING OUTCOME: Include at least one "Child can..." statement describing what the child will learn
${superSkillName ? `11. Align all content with the Super Skill: "${superSkillName}"` : ''}
${subSkillName ? `12. Focus on building the Sub-Skill: "${subSkillName}"` : ''}
${additionalContext ? `13. HIGH PRIORITY: Strictly follow the HIGH-PRIORITY CREATOR INSTRUCTIONS above.` : ''}

=== ABSOLUTELY FORBIDDEN CONTENT ===
NEVER use these words/phrases (they violate trauma-informed and ND-affirming principles):
- DEFICIT LANGUAGE: broken, damaged, wrong, faulty, disordered, deficit, dysfunction, abnormal, sick, diseased, problem brain, bad roads, wrong roads, messed up, not working properly, hard wired, set in stone, permanent
- FORBIDDEN METAPHORS: computer, hard drive, processor, muscle, empty vessel, blank slate, machine, engine, wires, circuits, channels, weather, waves, colours for emotions, seeds, driver, passenger, captain, pilot, volume dial, thermostat, meter, garden
- DIRECTIVE LANGUAGE: you need to, you must, you have to, you should, do this now, tell your parent, share your feelings, tell us about, you will
- EVALUATION LANGUAGE: good job, well done, great work, you got it right, correct answer, wrong answer, try harder, you scored, points, you only, you failed, score

USE INSTEAD:
- Invitation framing: "You might like to...", "You could try...", "Some children find it helpful to...", "One option is...", "If you'd like, you can..."
- Brain Town vocabulary: town, road, roads, street, streets, main street, motorway, highway, traffic, traffic light, traffic signal, building, buildings, town planner, brain town
- Strengths-based language: difference (not deficit), unique (not abnormal), developing (not broken)

=== AUSTRALIAN ENGLISH (MANDATORY) ===
All content MUST use Australian English spelling and conventions:
- colour (not color), behaviour (not behavior), favourite (not favorite)
- organise (not organize), recognise (not recognize), realise (not realize)
- practise (verb) / practice (noun), licence (noun) / license (verb)
- centre (not center), metre (not meter)
- mum (not mom), whilst, amongst
- Use "learnt" not "learned", "spelt" not "spelled" where appropriate

=== NATURAL LANGUAGE RULES (MANDATORY) ===
Write in a natural, human voice. Avoid patterns that sound like AI-generated text:
- NEVER use em dashes (—). Use commas, full stops, or rewrite the sentence instead.
- NEVER use hyphens or en dashes to join compound words in headings, labels, activity content, or descriptions. Use spaces instead. Examples: "thought feeling" NOT "thought-feeling", "feeling action" NOT "feeling-action", "self care" NOT "self-care". The only exception is internal code identifiers.
- NEVER use "Let's dive in", "dive into", "Unlock your", "Unleash", "delve into"
- Avoid overuse of exclamation marks (max 2-3 per page)
- Avoid starting consecutive sentences with the same word
- Vary sentence structure and length naturally
- Do not use overly enthusiastic or corporate-sounding phrases
- Write as a warm, experienced educator would speak, not as a marketing copywriter

${previousModuleSummary ? `=== PREVIOUS MODULE CONTEXT (Week ${(weekNumber || 1) - 1}) ===
This module is Week ${weekNumber || 'unknown'} in a series. The previous module covered:
${previousModuleSummary}

IMPORTANT: Build upon and progress from the previous module. Do NOT repeat the same content.
- Reference concepts already introduced (briefly, as revision)
- Introduce new skills that build on the foundation
- Deepen understanding of themes already explored
- Progress the learning journey forward
` : weekNumber === 1 ? `=== SERIES POSITION ===
This is Week 1 (the first module in the series). Establish foundational concepts that later weeks will build upon.
` : ''}

${reflectionPrompt ? `Reflection: "${reflectionPrompt}"` : ''}
${rewardText ? `Reward: "${rewardText}"` : ''}
`.trim();
}

// ====================
// PAGE STRUCTURE GENERATOR
// ====================

// Helper to shuffle arrays
function shuffleArray<T>(arr: T[]): T[] {
  const shuffled = [...arr];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

/**
 * Pedagogical stage for content progression
 * - introduce: First exposure to a concept (awareness, exploration)
 * - practice: Apply the concept in guided activities
 * - apply: Use the concept in new contexts, reflect on personal experience
 */
type PedagogicalStage = "introduce" | "practice" | "apply";

/**
 * Extended page template that includes pedagogical context
 */
interface PageTemplateWithContext extends PageTemplate {
  chapter?: number;
  pedagogicalStage?: PedagogicalStage;
  conceptFocus?: string; // What specific aspect to focus on (prevents repetition)
}

/**
 * Generate a variable page structure between MIN_PAGES and MAX_PAGES
 * 
 * KEY IMPROVEMENTS:
 * 1. Activities are distributed EVENLY across all 3 chapters (not clustered)
 * 2. Each chapter gets a MIX of activity types (intro, practice, apply)
 * 3. Pedagogical stages are assigned to guide content progression
 * 4. No two similar activities appear in the same chapter
 */
function generatePageStructure(): PageTemplate[] {
  const targetPages = randomInt(MIN_PAGES, MAX_PAGES);
  
  // CORE activities (classic, well-tested)
  const coreActivities: PageTemplate[] = [
    { type: "checklist",   starReward: true },
    { type: "reflection",  starReward: true },
    { type: "quiz",        starReward: true },
    { type: "drawing",     starReward: true },
    { type: "breathing",   starReward: true },
    { type: "scenario",    starReward: true },
  ];
  
  // FEELINGS-FOCUSED activities
  const feelingsActivities: PageTemplate[] = [
    { type: "feeling-thermometer", starReward: true },
    { type: "body-map",            starReward: true },
    { type: "feeling-selector",    starReward: true },
    { type: "emoji-check-in",      starReward: true },
  ];
  
  // CREATIVE activities
  const creativeActivities: PageTemplate[] = [
    { type: "calm-den-builder",    starReward: true },
    { type: "fill-in-story",       starReward: true },
    { type: "comic-strip",         starReward: true },
    { type: "affirmation-builder", starReward: true },
    { type: "gratitude-jar",       starReward: true },
  ];
  
  // COGNITIVE activities
  const cognitiveActivities: PageTemplate[] = [
    { type: "action-plan",         starReward: true },
    { type: "warning-signs",       starReward: true },
    { type: "matching-activity",   starReward: true },
    { type: "sorting-activity",    starReward: true },
    { type: "thought-bubbles",     starReward: true },
    { type: "agree-disagree",      starReward: true },
    { type: "word-scramble",       starReward: true },
    { type: "coping-cards",        starReward: true },
  ];
  
  // v5 NEW CHALLENGE activities (interactive games)
  const challengeActivities: PageTemplate[] = [
    { type: "weather-controller",  starReward: true },
    { type: "power-up-collector",  starReward: true },
    { type: "emotion-maze",        starReward: true },
    { type: "strength-shield",     starReward: true },
    { type: "feeling-volcano",     starReward: true },
  ];

  // v7 NEW HIGHLY INTERACTIVE GAME activities (the fun, engaging ones!)
  const gameActivities: PageTemplate[] = [
    { type: "balloon-pop",         starReward: true },
    { type: "treasure-hunt",       starReward: true },
    { type: "monster-tamer",       starReward: true },
    { type: "garden-grower",       starReward: true },
    { type: "superhero-creator",   starReward: true },
    { type: "feelings-orchestra",  starReward: true },
    { type: "calm-aquarium",       starReward: true },
    { type: "rocket-launcher",     starReward: true },
    { type: "magic-potion",        starReward: true },
    { type: "feelings-bingo",      starReward: true },
  ];
  
  // =====================
  // ACTIVITY SELECTION
  // =====================
  // Select activities ensuring variety across categories
  
  const allCategories = [
    { name: "core", items: shuffleArray(coreActivities), minPick: 2, maxPick: 3 },
    { name: "feelings", items: shuffleArray(feelingsActivities), minPick: 1, maxPick: 2 },
    { name: "creative", items: shuffleArray(creativeActivities), minPick: 1, maxPick: 2 },
    { name: "cognitive", items: shuffleArray(cognitiveActivities), minPick: 1, maxPick: 2 },
    { name: "challenge", items: shuffleArray(challengeActivities), minPick: 1, maxPick: 2 },
    { name: "games", items: shuffleArray(gameActivities), minPick: 2, maxPick: 3 },
  ];
  
  const selectedActivities: PageTemplate[] = [];
  for (const category of allCategories) {
    const count = randomInt(category.minPick, category.maxPick);
    selectedActivities.push(...category.items.slice(0, count));
  }
  
  // Shuffle all selected activities
  const shuffledActivities = shuffleArray(selectedActivities);
  
  // =====================
  // CHAPTER DISTRIBUTION
  // =====================
  // Distribute activities EVENLY across 3 chapters
  
  const fixedPages = 8; // cover + welcome + 3 chapter-dividers + summary + completion + admin
  const contentPages = Math.max(9, targetPages - fixedPages);
  
  // Calculate pages per chapter (roughly equal)
  const basePerChapter = Math.floor(contentPages / 3);
  const remainder = contentPages % 3;
  
  const chapterPageCounts = [
    basePerChapter + (remainder > 0 ? 1 : 0),
    basePerChapter + (remainder > 1 ? 1 : 0),
    basePerChapter,
  ];
  
  // Distribute activities into 3 buckets (one per chapter)
  const chapterActivities: PageTemplate[][] = [[], [], []];
  let activityIndex = 0;
  
  // Round-robin distribution ensures even spread
  while (activityIndex < shuffledActivities.length) {
    for (let ch = 0; ch < 3 && activityIndex < shuffledActivities.length; ch++) {
      chapterActivities[ch].push(shuffledActivities[activityIndex]);
      activityIndex++;
    }
  }
  
  // =====================
  // BUILD FINAL STRUCTURE
  // =====================
  
  const structure: PageTemplate[] = [
    { type: "cover",   starReward: false },
    { type: "welcome", starReward: false },
  ];
  
  /**
   * Build a chapter with proper pedagogical flow:
   * - Start with interactive lesson (introduce)
   * - Add lesson if early chapter (reinforce)
   * - Mix in activities from the chapter's allocation
   * - Ensure variety within the chapter
   */
  function buildChapter(chapterIdx: number, pagesNeeded: number, chapterActivityPool: PageTemplate[]): void {
    structure.push({ type: "chapter-divider", starReward: false });
    let filled = 0;
    
    // Each chapter starts with an interactive lesson (pedagogical anchor)
    structure.push({ type: "interactive-lesson", starReward: false });
    filled++;
    
    // Chapters 1 and 2 get a plain lesson for foundational teaching
    if (chapterIdx <= 2 && filled < pagesNeeded) {
      structure.push({ type: "lesson", starReward: false });
      filled++;
    }
    
    // Shuffle the chapter's activity pool for variety within the chapter
    const shuffledPool = shuffleArray([...chapterActivityPool]);
    let poolIndex = 0;
    
    // Fill remaining slots
    while (filled < pagesNeeded) {
      if (poolIndex < shuffledPool.length) {
        // Use activities from this chapter's pool
        structure.push(shuffledPool[poolIndex]);
        poolIndex++;
      } else {
        // Fallback: add interactive lesson (avoids repetitive plain lessons)
        structure.push(
          Math.random() > 0.5
            ? { type: "interactive-lesson", starReward: false }
            : { type: "lesson", starReward: false }
        );
      }
      filled++;
    }
  }
  
  // Build all three chapters
  buildChapter(1, chapterPageCounts[0], chapterActivities[0]);
  buildChapter(2, chapterPageCounts[1], chapterActivities[1]);
  buildChapter(3, chapterPageCounts[2], chapterActivities[2]);
  
  // Always end with summary and completion
  structure.push({ type: "summary",    starReward: false });
  structure.push({ type: "completion", starReward: false });
  
  // Admin-only verification page (always last)
  structure.push({ type: "admin-verification", starReward: false });
  
  return structure;
}

// ====================
// CLAUDE API
// ====================

async function getSettings(supabaseClient: any) {
  if (cachedSettings && Date.now() - cachedSettings.fetchedAt < CACHE_TTL_MS) {
    return cachedSettings;
  }
  
  const { data: settings, error } = await supabaseClient
    .from("settings")
    .select("claude_api_key")
    .single();
    
  if (error || !settings?.claude_api_key) {
    throw new Error("Claude API key not configured in settings");
  }
  
  cachedSettings = { claude_api_key: settings.claude_api_key, fetchedAt: Date.now() };
  return cachedSettings;
}

async function callClaude(
  apiKey: string,
  systemPrompt: string,
  userPrompt: string,
  maxTokens: number
): Promise<string> {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: maxTokens,
      temperature: CLAUDE_TEMPERATURE,
      system: systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
    }),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Claude API error: ${res.status} ${res.statusText}\n${errText}`);
  }

  const data = await res.json();
  return (data?.content?.[0]?.text ?? "").toString();
}

// ====================
// EXPORTS
// ====================

export {
  // Types
  type PageType,
  type PageTemplate,
  type ModuleMetadata,
  type SeriesInfo,
  type GeneratedContent,
  type LessonContent,
  type ChapterDivider,
  type ChecklistContent,
  type ReflectionContent,
  type QuizContent,
  type DrawingContent,
  type BreathingContent,
  type ScenarioContent,
  type SummaryContent,
  type CompletionContent,
  type FeelingThermometerContent,
  type BodyMapContent,
  type FeelingSelectorContent,
  type CalmDenBuilderContent,
  type ActionPlanContent,
  type WarningSingsContent,
  type MatchingActivityContent,
  type InteractiveLessonContent,
  type FillInStoryContent,
  type CopingCardsContent,
  type GratitudeJarContent,
  type SortingActivityContent,
  type ThoughtBubblesContent,
  type EmojiCheckInContent,
  type WordScrambleContent,
  type AgreeDisagreeContent,
  type ComicStripContent,
  type AffirmationBuilderContent,
  type WeatherControllerContent,
  type PowerUpCollectorContent,
  type EmotionMazeContent,
  type StrengthShieldContent,
  type FeelingVolcanoContent,
  type SpinTheWheelContent,
  type StickerCollectorContent,
  type MindfulAdventureContent,
  type EmotionDetectiveContent,
  type BalloonPopContent,
  type TreasureHuntContent,
  type MonsterTamerContent,
  type GardenGrowerContent,
  type SuperheroCreatorContent,
  type FeelingsOrchestraContent,
  type CalmAquariumContent,
  type RocketLauncherContent,
  type MagicPotionContent,
  type FeelingsBingoContent,
  type AgeRangeData,
  type CoreTheoryData,
  type VerificationReport,
  type ModuleSummary,
  type GrownUpNote,
  PAGE_TYPE_EVIDENCE_MAP,
  buildEnhancedContentBrief,
  
  // Configuration
  corsHeaders,
  CLAUDE_MODEL,
  CLAUDE_TEMPERATURE,
  TOKENS_METADATA,
  TOKENS_LESSON_BATCH,
  TOKENS_ACTIVITY,
  JOB_TIMEOUT_MS,
  CACHE_TTL_MS,
  MIN_PAGES,
  MAX_PAGES,
  
  // Utilities
  jsonResponse,
  escapeHtml,
  escapeForTemplate,
  escapeForOnclick,
  cleanJsonResponse,
  safeJsonParse,
  randomInt,
  shuffleArray,
  getAgeRangeKey,
  getAgeSpecificFormatting,
  
  // Claude API
  getSettings,
  callClaude,
  
  // Page Structure
  generatePageStructure,
};